# Generated by Django 3.1.2 on 2021-06-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='created_by',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
